# Generated by Django 4.2.3 on 2023-08-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsShop_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsShop_App.subcategory')),
            ],
        ),
    ]
