# Generated by Django 4.2.3 on 2023-08-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsShop_App', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
